### ISSUE TITLE
problem with Invoke-Retry

### ISSUE THREAD

**Issue by lipkau** [philips-software/powershell-cf-api#15]
The current implementation and usage of `Invoke-Retry` is causing huge delay in case of a login with wrong password, or setting space permissions for a user which does not exist.
also, it keeps you from using the server's response as output to the user (user is unable to see why something failed)

Let me know if you are interested in a PR for this.

**Comment by marklindell** [comment]
Invoke-Retry on passwords should exit on specific failures in that use case. PR would be great.
