### ISSUE TITLE
Need CI build with deployment

### ISSUE THREAD

**Issue by marklindell** [philips-software/powershell-cf-api#6]
Investigate using github actions and deploying to nuget.org

**Comment by JeroenKnoops** [comment]
We're trying to get the IT department to approve the publication to NuGet.

**Comment by marklindell** [comment]
I've learned that the appropriate location to publish public powershell modules is https://www.powershellgallery.com/ This allows native Install-Module within powershell. See https://github.com/philips-software/powershell-hsdp-iam as an example. This project will use the same. I'm going to close this issue and create a new one.

What does it mean for the IT depart to approve the publication to NuGet? This is opensource. Can't I publish anywhere on the internet I want?
